name: Publish nim-mmcif to PyPI

"on":
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "stable"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Nim dependencies
        run: nimble install -d

      - name: Compile Nim Python extension
        run: nimble buildPythonModule

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel
      
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w {dest_dir} {wheel}"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel -w {dest_dir} {wheel}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
  
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "stable"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          nimble install -d
      
      - name: Build source distribution
        run: python -m build --sdist
      
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publish-pypi:
    needs: [build, build-sdist]
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    environment:
      name: pypi
      url: https://pypi.org/p/nim-mmcif
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      
      - name: Flatten artifacts
        run: |
          mkdir -p final-dist
          find dist -name "*.whl" -exec cp {} final-dist/ \;
          find dist -name "*.tar.gz" -exec cp {} final-dist/ \;
      
      - name: Check distribution
        run: |
          pip install twine
          python -m twine check final-dist/*
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: final-dist/
