name: Publish nim-mmcif to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "stable"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Nim dependencies
        run: nimble install -d
      
      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine
      
      - name: Build Python modules for all platforms
        run: |
          # Build for Linux (current platform in CI)
          nimble buildPythonModule
          
          echo "Built module for distribution"
      
      - name: Build Python package
        run: python -m build
      
      - name: Check distribution
        run: python -m twine check dist/*
      
      - name: Publish to Test PyPI (optional)
        if: github.event.release.prerelease
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      
      - name: Publish to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1