name: Pytest
on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Nim
      run: |
        brew install nim

    - name: Install Nim dependencies
      run: |
        nimble install

    - name: Test
      run: |
        nimble test
