name: Pytest
on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Nim
      run: |
        brew install nim

    - name: Install Nim dependencies
      run: |
        nimble install

    - name: Build Python module
      run: |
        nimble buildPythonModule

    - name: Install pytest
      run: |
        pip install pytest

    - name: Test Nim
      run: |
        nimble test

    - name: Test Python bindings
      run: |
        python -m pytest tests/test_python_bindings.py -v
